with source as (
    select * from {{ source('sqlproxy.1184uzq0lnhd681emq2qs0yk33y6', 'raw_data') }}
),

renamed as (
    select
        -- Add column selection based on the fields in the datasource
        attribute_id, attribute_name, country_usda_code, calculation_1392175277239238660, calculation_700872758527991827, calculation_700872758530551828, calculation_700872758533533717, calculation_757167735445893120, calculation_930274800807022599, calculation_930274866357940224, calender_year, category, category_group, commodity, commodity_code, commodity_group, commodity_group_tableau, commodity_origin, commodityorigin_(level_3,_corn), commodityorigin_(level_3,_eu), commodityorigin_(level_3,_soy_beans), commodityorigin_(level_3,_soy_meal), commodityorigin_(level_3,_wheat), commodityorigin_(level_4,_corn), commodityorigin_(level_4,_oils), commodityorigin_(level_4,_soy_beans), commodityorigin_(level_4,_soy_meal), commodityorigin_(level_4,_wheat), cropyear, dest._group_(level_1,_corn), dest._group_(level_1,_oils_-_po_-_eu), dest._group_(level_1,_oils_-_po), dest._group_(level_1,_oils_-_rso_-_eu), dest._group_(level_1,_oils_-_rso), dest._group_(level_1,_oils_-_sbo_-_eu), dest._group_(level_1,_oils_-_sbo), dest._group_(level_1,_oils_-_sfo_-_eu), dest._group_(level_1,_oils_-_sfo), dest._group_(level_1,_soy_beans/meal), dest._group_(level_1,_wheat), dest._group_(level_2,_corn), dest._group_(level_2,_oils_-_po_-_eu), dest._group_(level_2,_oils_-_po), dest._group_(level_2,_oils_-_rso_-_eu), dest._group_(level_2,_oils_-_rso), dest._group_(level_2,_oils_-_sbo_-_eu), dest._group_(level_2,_oils_-_sbo), dest._group_(level_2,_oils_-_sfo_-_eu), dest._group_(level_2,_oils_-_sfo), dest._group_(level_2,_soy_beans/meal), dest._group_(level_2,_wheat), dest._group_(level_3,_eu), destination, export_date_time_(copy)_700872755466481664, export_date_time, indicator, market_year_(reference), market_year_(yyyy), origin, origin_(level_3), origin_(level_3)_*, origin_(level_4), origin_(level_4)_*, origin_group_(level_3,_corn), origin_group_(level_3,_eu), origin_group_(level_3,_oils), origin_group_(level_3,_soy_beans), origin_group_(level_3,_soy_meal), origin_group_(level_4,_corn), origin_group_(level_4,_oils), origin_group_(level_4,_soy_beans), origin_group_(level_4,_soy_meal), origin_group_(level_4,_wheat)_, period_(yyyy/mm), product_segment, parameter_1_1, source, usda_market_year, unit_description, unit_id, volume_(000mt), volume_(mbu), volume_(mbu)_round_(copy)_930274866395406337
    from source
)

select * from renamed